/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TournamentDAO;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Tournament;
import model.User;

/**
 *
 * @author Vinh
 */
public class BTCManagerFrm extends javax.swing.JFrame {

    private User user;

    public BTCManagerFrm(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("BTC Manager Home");

        jLabel2.setText("Login as "+user.getName());

        jButton1.setText("Quản lý thông tin giải đấu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xếp cặp thi đấu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Danh sách cờ thủ thi đấu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xem bảng kết quả vòng đấu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cập nhập kết quả");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Thống kê thay đổi Elo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((evt.getSource() instanceof JButton) && (((JButton) evt.getSource()).equals(jButton1))) {
            (new TournamentManagerFrm(user)).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        (new LoginFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TournamentDAO tournamentDAO=new TournamentDAO();
        ArrayList <Tournament> listTournament=new ArrayList();
        listTournament=tournamentDAO.findAll();
        boolean test=false;
        for(Tournament i:listTournament){
            if(i.trangThai().compareTo("Dang dien ra")==0){
                test=true;
                (new ListPlayerFrm(user, tournamentDAO.get(i.getId()))).setVisible(true);
                this.dispose();
                break;
            }
        }
        if(test==false){
            JOptionPane.showMessageDialog(this, "Hien chua co giai dau nao!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TournamentDAO tournamentDAO=new TournamentDAO();
        ArrayList <Tournament> listTournament=new ArrayList();
        listTournament=tournamentDAO.findAll();
        boolean test=false;
        for(Tournament i:listTournament){
            if(i.trangThai().compareTo("Dang dien ra")==0){
                test=true;
                Tournament tournament=tournamentDAO.get(i.getId());
                if(tournament.getListRound().size()==0){
                    JOptionPane.showMessageDialog(this, "Hay kiem tra xem so luong nguoi da du chua de bat dau giai dau");
                }
                else{
                    if(tournament.statusRound()==false){
                        JOptionPane.showMessageDialog(this, "Vong dau hien tai chua ket thuc");
                    }
                    else{
                        (new ScheduledFrm(user, tournament)).setVisible(true);
                        this.dispose();
                        break;
                    }
                }
            }
        }
        if(test==false){
            JOptionPane.showMessageDialog(this, "Hien chua co giai dau nao, hoac giai dau da ket thuc!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TournamentDAO tournamentDAO=new TournamentDAO();
        ArrayList <Tournament> listTournament=new ArrayList();
        listTournament=tournamentDAO.findAll();
        boolean test=false;
        for(Tournament i:listTournament){
            if(i.trangThai().compareTo("Dang dien ra")==0){
                test=true;
                Tournament tournament=tournamentDAO.get(i.getId());
                if(tournament.getListRound().size()==0){
                    JOptionPane.showMessageDialog(this, "Hay kiem tra du nguoi de bat dau giai dau!!"); 
                }
                else{
                    if(tournament.statusRound()==false){
                        (new SelectMatchFrm(user, tournament)).setVisible(true);
                        this.dispose();
                        break;
                    }
                    else{
                       JOptionPane.showMessageDialog(this, "Cac tran dau trong vong dau hien tai da ket thuc!!"); 
                    }
                }
            }
        }
        if(test==false){
            JOptionPane.showMessageDialog(this, "Hien chua co giai dau nao, hoac giai dau da ket thuc!!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TournamentDAO tournamentDAO=new TournamentDAO();
        ArrayList <Tournament> listTournament=new ArrayList();
        listTournament=tournamentDAO.findAll();
        boolean test=false;
        for(Tournament i:listTournament){
            if(i.trangThai().compareTo("Dang dien ra")==0){
                test=true;
                Tournament tournament= tournamentDAO.get(i.getId());
                (new SelectRoundFrm(user, tournament)).setVisible(true);
                this.dispose();
                break;
            }
        }
        if(test==false){
            JOptionPane.showMessageDialog(this, "Hien chua co giai dau nao, hoac giai dau da ket thuc!!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        (new SelectTournamentFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
