/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PlayerDAO;
import dao.StatMatchDAO;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import model.ChessPlayer;
import model.Player;
import model.Round;
import model.StatMatch;
import model.Tournament;
import model.User;

/**
 *
 * @author Vinh
 */
public class BXHRoundFrm extends javax.swing.JFrame {

    /**
     * Creates new form BXHRoundFrm
     */
    private User user;
    private Tournament tournament;
    private Round round;
    private ArrayList<Player> list;
    public BXHRoundFrm(User user, Tournament tournament, Round round) {
        list=new ArrayList();
        this.user=user;
        this.tournament=tournament;
        this.round=round;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("BXH Round "+round.getStt());

        PlayerDAO playerDAO=new PlayerDAO();
        list=playerDAO.findByTournament(tournament.getId());
        for(Player i:list){
            tournament.setTongDiem(i, round.getStt());
        }
        Collections.sort(list);
        String[] columnNames = {"Id", "Name", "Year", "Nationality", "Elo", "Score"};
        String[][] value = new String[list.size()][6];
        for(int i=0; i<list.size(); i++){
            ChessPlayer temp=list.get(i).getChessPlayer();
            StatMatchDAO smDAO=new StatMatchDAO();
            StatMatch sm=smDAO.getById(round.idMatchForRound(list.get(i).getId()));
            value[i][0]=temp.getId()+"";
            value[i][1]=temp.getName();
            value[i][2]=temp.getYear()+"";
            value[i][3]=temp.getNationality();
            if(sm.getPlayer1().getId()==list.get(i).getId()){
                value[i][4]=(sm.getPlayer1().getChessPlayer().getElo())+"";
            }
            else{
                value[i][4]=(sm.getPlayer2().getChessPlayer().getElo())+"";
            }
            value[i][5]=list.get(i).getTongDiem()+"";
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames);
        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        (new SelectRoundFrm(user, tournament)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
