/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PlayerDAO;
import dao.StatPlayerDAO;
import dao.TournamentDAO;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import model.Player;
import model.StatPlayer;
import model.Tournament;
import model.User;

/**
 *
 * @author Vinh
 */
public class StatEloFrm extends javax.swing.JFrame {

    /**
     * Creates new form StatEloFrm
     */
    private User user;
    private Tournament tournament;
    private ArrayList <Player> listPlayer;
    private ArrayList <StatPlayer> listStat;
    public StatEloFrm(User user, Tournament tournament) {
        this.user=user;
        this.tournament=tournament;
        listStat=new ArrayList();
        PlayerDAO playerDAO=new PlayerDAO();
        listPlayer=playerDAO.findByTournament(this.tournament.getId());
        for(Player i:listPlayer){
            StatPlayerDAO spDAO=new StatPlayerDAO();
            listStat.add(spDAO.getById(i.getId()));
        }
        for(int i=0; i<listStat.size()-1; i++){
            for(int j=i+1; j<listStat.size(); j++){
                if(listStat.get(i).compareTo(listStat.get(j))==-1){
                    StatPlayer temp=listStat.get(i);
                    listStat.set(i, listStat.get(j));
                    listStat.set(j, temp);
                }
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        String[] columnNames = {"Id", "Name", "Year", "Nationality", "Elo Old", "Elo New", "Elo Change"};
        String[][] value = new String[listStat.size()][7];
        for (int i = 0; i < listStat.size(); i++) {
            value[i][0] = listStat.get(i).getChessPlayer().getId() + "";
            value[i][1] = listStat.get(i).getChessPlayer().getName();
            value[i][2] = listStat.get(i).getChessPlayer().getYear()+"";
            value[i][3] = listStat.get(i).getChessPlayer().getNationality();
            value[i][4] = listStat.get(i).getEloOld()+"";
            value[i][5] = listStat.get(i).getEloNew()+"";
            value[i][6] = listStat.get(i).getEloChange()+"";
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames);
        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Tournament "+ this.tournament.getName());

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        (new SelectTournamentFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRowIndex=jTable1.getSelectedRow();
        StatPlayer statPlayer=this.listStat.get(selectedRowIndex);
        (new StatDetailPlayerFrm(user, this.tournament, statPlayer)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
